gui:
  border: single

  screenMode: half

  filterMode: fuzzy

  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"

git:
  autoFetch: false

  autoRefresh: false

  log:
    showGraph: never
